version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-246-201.compute-1.amazonaws.com
            port: '5432'
            database: dbadq3c1ttjc01
            password: 7c09223827b43af63e328f6aa23f4764a78ee8de6edac42ecbe22523ccaa6e4f

            ssl: true
            user: hlkfvgvivxdpjw
            migrations: true
            rawAccess: true
